// Canonical genre map (#34): fold aliases and case variants to one spelling
// so filtering and display stay consistent. Keys are lowercase aliases.
const GENRE_ALIASES: Record<string, string> = {
  'drum & bass': 'Drum and Bass',
  'drum and bass': 'Drum and Bass',
  dnb: 'Drum and Bass',
  "drum'n'bass": 'Drum and Bass',
  'drum n bass': 'Drum and Bass',
  'hip-hop/rap': 'Hip-Hop',
  'hip hop': 'Hip-Hop',
  'hip-hop': 'Hip-Hop',
  'r&b': 'R&B',
  'rnb': 'R&B',
  'rhythm and blues': 'R&B',
  'edm': 'Electronic',
  'electronic': 'Electronic',
  'electro': 'Electro',
  'dance': 'Dance',
  'house': 'House',
  'deep house': 'Deep House',
  'tech house': 'Tech House',
  'techno': 'Techno',
  'hard techno': 'Hard Techno',
  'minimal techno': 'Minimal Techno',
  'trance': 'Trance',
  'garage': 'Garage',
  'uk garage': 'UK Garage',
  'dubstep': 'Dubstep',
  'breaks': 'Breaks',
  'breakbeat': 'Breaks',
  'disco': 'Disco',
  'nu-disco': 'Nu-Disco',
  'funk': 'Funk',
  'boogie': 'Boogie',
  'soul': 'Soul',
  'jazz': 'Jazz',
  'reggae': 'Reggae',
  'dub': 'Dub',
  'dancehall': 'Dancehall',
  'afro house': 'Afro House',
  'afrobeats': 'Afrobeats',
  'latin': 'Latin',
  'ambient': 'Ambient',
  'downtempo': 'Downtempo',
  'trip-hop': 'Trip-Hop',
  'pop': 'Pop',
  'k-pop': 'K-Pop',
  'rock': 'Rock',
  'alternative': 'Alternative',
  'indie': 'Indie',
  'country': 'Country',
  'folk': 'Folk',
  'classical': 'Classical',
  'metal': 'Metal',
  'punk': 'Punk',
  'eclectic': 'Eclectic',
  'experimental': 'Experimental',
  'world': 'World',
  'lounge': 'Lounge',
  'chillout': 'Chillout',
  'liquid drum and bass': 'Liquid Drum and Bass',
  'liquid dnb': 'Liquid Drum and Bass',
  'liquid funk': 'Liquid Funk',
  'neurofunk': 'Neurofunk',
  'jungle': 'Jungle',
  '2-step': '2-Step',
  'grime': 'Grime',
  'bass music': 'Bass Music',
  'footwork': 'Footwork',
  'juke': 'Juke',
  'synthwave': 'Synthwave',
  'retrowave': 'Synthwave',
  'minimal': 'Minimal',
  'melodic techno': 'Melodic Techno',
  'progressive house': 'Progressive House',
  'acid house': 'Acid House',
  'acid techno': 'Acid Techno',
  'detroit techno': 'Detroit Techno',
  'deep dubstep': 'Deep Dubstep',
  'uk bass': 'UK Bass',
  'gqom': 'Gqom',
  'amapiano': 'Amapiano',
  'baile funk': 'Baile Funk',
  'cumbia': 'Cumbia',
  'psytrance': 'Psytrance',
  'goa trance': 'Goa Trance',
  'hardcore': 'Hardcore',
  'hardstyle': 'Hardstyle',
  'happy hardcore': 'Happy Hardcore',
  'gabber': 'Gabber',
};

export function normaliseGenre(genre: string): string {
  const key = genre.trim().toLowerCase();
  return GENRE_ALIASES[key] ?? genre.trim();
}

export function normaliseGenres(genres: string[]): string[] {
  return [...new Set(genres.map(normaliseGenre).filter(Boolean))];
}
